
name: Guidelines Publishing
on:
  push:
    branches:
      - master
jobs:
  add-html:
    name: Add Html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: replace head tags with extra html
        run: |
          cd www
          printf '<li> <a href="%s">\n' *.html > filelist.txt
          printf '%s</a></li>\n' *.html > filelist2.txt
          sed -i -e 's|_| |g' filelist2.txt 
          sed -i -e ':a;s/html/\n/;s/MeG.*\n//;ta' filelist2.txt
          paste -d " " filelist.txt filelist2.txt > filelist3.txt
          find . -name '*.html' -exec sed -i -e 's|</head>|\<script\ src\=\"myScript.js\"\>\</script\>\<link rel\=\"stylesheet\"\ href\=\"myStyle.css\"\>\</head\>|g' -e 's|<body>|<body>\ \<div w3-include-html\=\"panel.html\"\>\</div\>\ \<script\>\ includeHTML\(\)\;\ \</script\>|g' {} \;
          cat prefix.txt filelist3.txt postfix.txt > panel.html
          cp Introduction_and_abbreviations_MeG-CLS-047.html index.html
          sed -i -e 's|</head>|\<script\ src\=\"ManUp.js\"\>\</script\>\<link rel\=\"manifest\"\ href\=\"manifest.json\"\>\</head\>|g' index.html
          mv *.html ..
        shell: bash
      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name ${{ github.actor}}
          git config --local user.email ${{ github.actor}}@users.noreply.github.com
          git add .
          git commit -m "Updating the repository GitHub html pages in the www folder"
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true      



